{% set name = "pylsp-mypy" %}
{% set version = "0.6.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa5d547b25ca431b5b17689c495c55aa374b19b35c59746987e417044fb722ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - mypy
    - python >=3.6
    - python-lsp-server
    - toml

test:
  imports:
    - pylsp_mypy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Richardk2n/pylsp-mypy
  summary: Mypy linter for the Python LSP Server.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - dhirschfeld
