{% set name = "pylsp-mypy" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f651f1cd2ca86eabe27082da904467a0edc1d2ea2e36f130fdde00eea960f0da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - mypy
    - python >=3.6
    - python-lsp-server

test:
  imports:
    - pylsp_mypy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Richardk2n/pylsp-mypy
  summary: Mypy linter for the Python LSP Server.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - dhirschfeld
