{% set name = "pylsp-mypy" %}
{% set version = "0.6.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f8307ca07d7e253e50e38c5fe31c371ceace0bc33d31c3429fa035d6d41bd5f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - mypy >=0.981
    - python >=3.7
    - python-lsp-server >=1.7.0
    - tomli >=1.1.0

test:
  imports:
    - pylsp_mypy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Richardk2n/pylsp-mypy
  summary: Mypy linter for the Python LSP Server.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - dhirschfeld
