{% set name = "mypy-ls" %}
{% set version = "0.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27cfe0b30c2356b743979f24cb396c8d113d32808c88b757a373e03b49502a4b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - mypy
    - python >=3.6
    - python-language-server >=0.34.0

test:
  imports:
    - mypy_ls
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Richardk2n/pyls-mypy
  summary: Mypy linter for the Python Language Server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
