{% set name = "pylsp-mypy" %}
{% set version = "0.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7a7d3117ea0361cae2ed00614195d36f4c157a06116c8792449e19f57319ddbf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - mypy >=0.981
    - python >={{ python_min }}
    - python-lsp-server >=1.13.1
    - tomli >=1.1.0

test:
  imports:
    - pylsp_mypy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Richardk2n/pylsp-mypy
  summary: Mypy linter for the Python LSP Server.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - dhirschfeld
